version: '2'
services:
  postgresql:
    container_name: berp_postgresql
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  odoo:
    container_name: berp_odoo
    image: 'docker.io/bitnami/odoo:12-debian-10'
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
      - './addons:/home/odoojas'
      - './addons_externos:/home/addons_externos'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local