{
    'name': "berp",
    'version': '1.0',
    'depends': ['base'],
    'author': "Pau Barbarroja",
    'category': 'berp',
    'description': """berp""",
    'data': [
        'categorias/categoria.xml',
        'eventos/evento.xml',
        'eventos/inscripcion_evento.xml',
        'marcas/marca.xml',
        'pistas/pista.xml',
        'pruebas/prueba.xml',
        'socios/socio.xml',
        'grupos_entreno/grupo_entreno.xml',
        'puntos_hungaros/puntos_hungaros.xml',
        'security/security.xml',
        'eventos/ir.model.access.xml',
        'grupos_entreno/ir.model.access.xml',
        'categorias/ir.model.access.xml',
        'marcas/ir.model.access.xml',
        'pistas/ir.model.access.xml',
        'pruebas/ir.model.access.xml',
        'puntos_hungaros/ir.model.access.xml',
        'socios/ir.model.access.xml',
        'menu.xml',
    ],
    'demo': [],
    'application': True,
}
# -*- coding: utf-8 -*-
